# Generated by Django 5.2.1 on 2025-05-26 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="converted_amount",
            field=models.FloatField(default=0),
        ),
    ]
